 # Simplificando pandas, lectura y escritura de archivos I

 Importamos las librerias a utilizar

In [2]:
import os
from pathlib import Path
import glob
import numpy as np
import pandas as pd

 # ¿Qué es pandas?

 [**pandas**](https://pandas.pydata.org/)

 **pandas** es una librería de código abierto con licencia BSD que
 proporciona estructuras de datos de alto rendimiento y fáciles de usar
 y herramientas de análisis de datos para el lenguaje de programación Python.

 ## Estructuras de pandas

 ### Series

 Arreglo unidimensional (vector), homogéneo y etiquetado.

 Creación de una Serie con una lista de valores

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=['a', 'b', 'c', 'd', 'e', 'f'])
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
dtype: float64

  ### Dataframes

 Estructura tabular bidimensional, de tamaño modificable, etiquetada

 con columnas potencialmente heterogéneas.

 Creación de un DataFrame usando un array de NumPy, fecha como índice (index)
 y  columnas etiquetadas:

In [4]:
dates = pd.date_range('20180501', periods=6)
dates

DatetimeIndex(['2018-05-01', '2018-05-02', '2018-05-03', '2018-05-04',
               '2018-05-05', '2018-05-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2018-05-01  1.344101  0.325384  0.215167  1.714706
2018-05-02 -0.243342 -0.646859  0.512364  0.364707
2018-05-03  1.389956  0.656840  0.893667 -0.830456
2018-05-04 -1.039423  0.043354  0.611307 -0.110691
2018-05-05  0.239502  0.485253 -0.321218  2.468113
2018-05-06  0.409115 -0.619463  0.775242 -1.029935

 Creación de un DataFrame usando diccionarios (dic)

In [6]:
df2 = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'}, index = ['f', 'g', 'h', 'i'])
df2

     A          B   C  D      E    F
f  1.0 2013-01-02 NaN  3   test  foo
g  1.0 2013-01-02 NaN  3  train  foo
h  1.0 2013-01-02 NaN  3   test  foo
i  1.0 2013-01-02 NaN  3  train  foo

 # Módulo pathlib

In [7]:
# directorio actual
dir_prin = Path.cwd()
dir_prin

WindowsPath('c:/Users/Waltter/OneDrive/Canal/Code/07-pandas_csv')

In [8]:
# directorio con los datos
dir_entra = dir_prin/'entradas'
dir_entra

WindowsPath('c:/Users/Waltter/OneDrive/Canal/Code/07-pandas_csv/entradas')

In [9]:
# directorio con los datos intermedios
dir_inter = dir_prin /'intermedios'
dir_inter

WindowsPath('c:/Users/Waltter/OneDrive/Canal/Code/07-pandas_csv/intermedios')

In [10]:
# directorio con los datos finales
dir_salid = dir_prin / 'salidas'
dir_salid

WindowsPath('c:/Users/Waltter/OneDrive/Canal/Code/07-pandas_csv/salidas')

 # Lectura desde archivos csv

 ## Un archivo

In [11]:
datos = pd.read_csv(dir_entra / 'ejemplo.csv')

In [12]:
# Observar las primeras filas
datos.head()

,2,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
0,5.0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
1,3.0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
2,1.0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
3,1.0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
4,NaN,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility

In [13]:
datos = pd.read_csv(dir_entra / 'ejemplo.csv', skiprows=5)
datos.head(10)

,Unnamed: 0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
0,1,2018-01-01 00:00,0.0,22.44,22.73,18.10,0.77,NaN,0.00,0.19,0.0,10.01
1,2,2018-01-01 01:00,0.0,21.88,22.15,17.75,0.77,NaN,0.00,NaN,0.0,10.01
2,3,2018-01-01 02:00,0.0,21.33,21.63,17.94,0.81,NaN,0.00,NaN,0.0,10.01
3,4,2018-01-01 03:00,0.0,20.77,21.07,17.75,0.83,NaN,0.00,NaN,0.0,10.01
4,5,2018-01-01 04:00,0.0,19.11,19.33,16.79,0.86,NaN,0.00,NaN,0.0,10.01
5,6,2018-01-01 05:00,0.0,21.63,21.80,16.91,0.75,NaN,0.00,NaN,0.0,10.01
6,7,2018-01-01 06:00,0.0,20.23,20.44,17.01,0.82,1014.90,3.85,0.38,0.0,10.01
7,8,2018-01-01 07:00,0.0,21.19,21.37,16.91,0.77,NaN,0.00,0.19,0.0,10.01
8,9,2018-01-01 08:00,0.0,24.00,24.24,17.83,0.68,NaN,3.93,0.19,1.0,10.01
9,10,2018-01-01 09:00,0.0,25.14,25.36,17.63,0.63,1016.29,9.40,0.38,3.0,10.01

In [14]:
# Observar las últimas filas
datos.tail(6)

,Unnamed: 0,time,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
738,739,2018-01-31 18:00,0.0,25.66,25.81,16.86,0.58,NaN,16.00,NaN,0.0,10.01
739,740,2018-01-31 19:00,0.0,23.34,23.42,16.31,0.65,NaN,8.10,NaN,0.0,10.01
740,741,2018-01-31 20:00,0.0,23.00,23.09,16.48,0.67,NaN,6.05,NaN,0.0,10.01
741,742,2018-01-31 21:00,0.0,23.00,23.04,15.99,0.65,NaN,9.66,NaN,0.0,10.01
742,743,2018-01-31 22:00,0.0,22.25,22.29,15.99,0.68,NaN,1.61,NaN,0.0,10.01
743,744,2018-01-31 23:00,0.0,21.69,21.73,15.86,0.69,NaN,1.13,NaN,0.0,10.01

In [15]:
# Dimensiones del Dataframe
datos.shape

(744, 12)

In [16]:
# Nombre de las columnas
datos.columns

Index(['Unnamed: 0', 'time', 'precipIntensity', 'temperature',
       'apparentTemperature', 'dewPoint', 'humidity', 'pressure', 'windSpeed',
       'cloudCover', 'uvIndex', 'visibility'],
      dtype='object')

In [17]:
# Index
datos.index

RangeIndex(start=0, stop=744, step=1)

In [18]:
# Información de las columnas
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 12 columns):
Unnamed: 0             744 non-null int64
time                   744 non-null object
precipIntensity        744 non-null float64
temperature            744 non-null float64
apparentTemperature    744 non-null float64
dewPoint               744 non-null float64
humidity               744 non-null float64
pressure               92 non-null float64
windSpeed              744 non-null float64
cloudCover             226 non-null float64
uvIndex                550 non-null float64
visibility             739 non-null float64
dtypes: float64(10), int64(1), object(1)
memory usage: 66.9+ KB

In [19]:
# Tipos de datos
datos.dtypes

Unnamed: 0               int64
time                    object
precipIntensity        float64
temperature            float64
apparentTemperature    float64
dewPoint               float64
humidity               float64
pressure               float64
windSpeed              float64
cloudCover             float64
uvIndex                float64
visibility             float64
dtype: object

 Más sobre [tipos de datos en python](https://data-flair.training/blogs/python-variables-and-data-types/)

 ### Eliminar una columna y cambiar el index

In [20]:
datosv2 = datos.drop(['Unnamed: 0'], axis=1)
datosv2 = datosv2.set_index('time')
datosv2.head()

,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
time,,,,,,,,,,
2018-01-01 00:00,0.0,22.44,22.73,18.10,0.77,NaN,0.0,0.19,0.0,10.01
2018-01-01 01:00,0.0,21.88,22.15,17.75,0.77,NaN,0.0,NaN,0.0,10.01
2018-01-01 02:00,0.0,21.33,21.63,17.94,0.81,NaN,0.0,NaN,0.0,10.01
2018-01-01 03:00,0.0,20.77,21.07,17.75,0.83,NaN,0.0,NaN,0.0,10.01
2018-01-01 04:00,0.0,19.11,19.33,16.79,0.86,NaN,0.0,NaN,0.0,10.01

In [21]:
# Resumen estadístico
datosv2.describe()

,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
count,744.000000,744.000000,744.000000,744.000000,744.000000,92.000000,744.000000,226.000000,550.000000,739.000000
mean,0.003417,23.676828,23.968911,15.943280,0.631868,1013.697609,6.613763,0.319336,0.949091,10.006238
std,0.087890,3.624720,3.918883,2.557113,0.119676,2.834807,6.118495,0.189310,2.063904,0.071745
min,0.000000,15.640000,15.640000,8.730000,0.340000,1000.810000,0.000000,0.000000,0.000000,8.630000
25%,0.000000,20.770000,20.967500,14.305000,0.540000,1012.270000,1.655000,0.190000,0.000000,10.010000
50%,0.000000,23.055000,23.205000,16.245000,0.640000,1014.045000,5.320000,0.190000,0.000000,10.010000
75%,0.000000,26.465000,26.642500,17.837500,0.710000,1015.570000,9.762500,0.440000,0.000000,10.010000
max,2.395200,32.110000,34.260000,21.940000,1.000000,1018.910000,31.210000,1.000000,8.000000,10.010000

In [22]:
# Valor de correlación lineal entre columnas
datosv2.corr()

,precipIntensity,temperature,apparentTemperature,dewPoint,humidity,pressure,windSpeed,cloudCover,uvIndex,visibility
precipIntensity,1.000000,-0.011450,-0.007576,0.067761,0.078216,-1.557024e-01,-0.022784,0.018847,-0.020835,2.048446e-03
temperature,-0.011450,1.000000,0.995988,0.515340,-0.672548,-3.504611e-01,0.267242,-0.202636,0.669280,-4.451623e-03
apparentTemperature,-0.007576,0.995988,1.000000,0.555388,-0.635117,-4.108814e-01,0.241933,-0.204376,0.666890,-3.108271e-03
dewPoint,0.067761,0.515340,0.555388,1.000000,0.278692,-7.794653e-01,-0.230059,-0.137634,0.245027,-3.346838e-02
humidity,0.078216,-0.672548,-0.635117,0.278692,1.000000,-3.851452e-01,-0.508523,0.111171,-0.563993,-1.692519e-02
pressure,-0.155702,-0.350461,-0.410881,-0.779465,-0.385145,1.000000e+00,0.436197,0.184996,0.091017,1.915374e-13
windSpeed,-0.022784,0.267242,0.241933,-0.230059,-0.508523,4.361965e-01,1.000000,-0.067205,0.308071,5.356197e-02
cloudCover,0.018847,-0.202636,-0.204376,-0.137634,0.111171,1.849960e-01,-0.067205,1.000000,-0.183211,1.597456e-01
uvIndex,-0.020835,0.669280,0.666890,0.245027,-0.563993,9.101665e-02,0.308071,-0.183211,1.000000,-8.901127e-02
visibility,0.002048,-0.004452,-0.003108,-0.033468,-0.016925,1.915374e-13,0.053562,0.159746,-0.089011,1.000000e+00